base:
  experiment_name: base # Should be overwriten in exp files

data:
  dataset_name: kits # only kits and adc supported
  dataset_path: /dtu/3d-imaging-center/courses/02510/data/KiTS19
  image_dims: [256, 256,-1] # what size should the images/volumes be resized to
  voxel_dims: [1.464845, 1.464845, 10.0] # what size should the voxels be resized to. this value is found in a notebook beforehand
  image_width: 640
  image_height: 360

  pct_train_split: 0.7 
  pct_val_split  : 0.2
  pct_test_split : 0.1

hyperparameters:
  path_to_weights: ~  # if not None will continue training from these weights. path to the weights, should be in the /models/ dir
  seed: 1312
  batch_size: 2
  epochs: 5
  learning_rate: 1e-5
  max_num_iterations: 10_000 # how many iterations to run / stop at (if n epochs and max time is large enough)
  max_training_time: 3600 # in seconds, how long to train for (if max_iterations and n epochs is large enough)


wandb:
  mode: disabled # "disabled" or "online" or "offline"
  team_name: deeplearning_3d
  project_name: tennis-court-tracking
  train_log_interval: 100
  validation_log_interval: 50