# 2D DynUNet fine-tuned on Dataset B for m iterations.

defaults:
  - config
  - _self_

base:
  experiment_name: finetune2d

model:
  path_to_weights: models/baseline2d/baseline2d_final.pt # the final baseline model

hyperparameters: 
  learning_rate: 1e-5
  max_training_time: 3600 # one hour

data:
  use_dataset_a: false # use dataset b, used for finetuning

wandb:
  mode: online
  run_name: finetune2d