# 3D DynUNet fine-tuned on Dataset B for m iterations.

defaults:
  - config
  - _self_

base:
  experiment_name: transfer2d3d

model:
  continue_from: baseline2d_final.pt # the final baseline model
  num_dimensions: 3   # 2 or 3 - for 2D or 3D nothing else pls
  use_modulewise_init: true

data:
  use_dataset_a: false # use dataset b, used for finetuning
  image_dims: [256, 256, 32] # what size should the images/volumes be resized to 38 is the median of the 'A' dataset
  crop_size: [-1, -1, -1] # whether to crop the 3D volume to a 2d slice, if [-1,-1,1] will crop. if [-1,-1,-1] wont crop. kinda shitty way of doing it
  voxel_dims: [1.464845, 1.464845, 10.0]

hyperparameters: 
  learning_rate: 1e-5
  max_training_time: 7200 # one hour

wandb:
  mode: online
  run_name: transfer2d3d